name: Grain CI Workflow
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Test WSL
        run: |
          wsl.exe --help
